"use client";

import { useCallback, useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import * as THREE from "three";

type Props={onClear:()=>void};
type FighterParts={group:THREE.Group;leftArm:THREE.Group;rightArm:THREE.Group;leftLeg:THREE.Group;rightLeg:THREE.Group;body:THREE.Mesh;face:THREE.Mesh};
type Enemy={fighter:FighterParts;health:number;active:boolean;attackCooldown:number;hitFlash:number;homeZ:number};
type InputState={left:boolean;right:boolean;up:boolean;down:boolean};

const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const material=(color:number,roughness=.66,metalness=.04)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const shadow=<T extends THREE.Mesh>(mesh:T)=>{mesh.castShadow=true;mesh.receiveShadow=true;return mesh;};

function limb(radius:number,length:number,color:THREE.Material){const mesh=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(radius,length,8,16),color));mesh.position.y=-length*.48;return mesh;}

function createMina():FighterParts{
  const group=new THREE.Group();group.name="リアル寄り3Dのミナ";
  const skin=material(0xd6a37f,.78),hair=material(0x211b1b,.88),coat=material(0xd5a93e,.6),shirt=material(0xe8e1cf,.82),dark=material(0x26312f,.72),boot=material(0x332a27,.65),white=material(0xf8f4e9,.5),iris=material(0x3c3028,.45);
  const body=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(.43,.92,10,22),coat));body.position.y=2.28;body.scale.set(.88,1,.66);group.add(body);
  const lapelL=shadow(new THREE.Mesh(new THREE.BoxGeometry(.16,.72,.05),shirt));lapelL.position.set(-.1,2.42,.38);lapelL.rotation.z=-.19;group.add(lapelL);const lapelR=lapelL.clone();lapelR.position.x=.1;lapelR.rotation.z=.19;group.add(lapelR);
  const belt=shadow(new THREE.Mesh(new THREE.BoxGeometry(.7,.11,.55),dark));belt.position.set(0,1.78,0);group.add(belt);
  const neck=shadow(new THREE.Mesh(new THREE.CylinderGeometry(.14,.17,.28,16),skin));neck.position.y=3.04;group.add(neck);
  const face=shadow(new THREE.Mesh(new THREE.SphereGeometry(.48,36,28),skin));face.scale.set(.82,1.06,.88);face.position.set(0,3.55,.02);group.add(face);
  const hairCap=shadow(new THREE.Mesh(new THREE.SphereGeometry(.5,34,24,0,Math.PI*2,0,Math.PI*.6),hair));hairCap.position.set(0,3.72,-.02);group.add(hairCap);
  const hairBack=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(.35,.78,9,18),hair));hairBack.position.set(0,3.28,-.34);hairBack.scale.z=.7;group.add(hairBack);
  [-1,1].forEach(side=>{const strand=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(.065,.62,7,12),hair));strand.position.set(side*.36,3.35,.05);strand.rotation.z=side*.11;group.add(strand);});
  [-.15,.15].forEach(x=>{const eye=shadow(new THREE.Mesh(new THREE.SphereGeometry(.061,16,10),white));eye.scale.set(1,.72,.45);eye.position.set(x,3.61,.43);group.add(eye);const pupil=shadow(new THREE.Mesh(new THREE.SphereGeometry(.029,12,8),iris));pupil.position.set(x,3.61,.472);group.add(pupil);const brow=shadow(new THREE.Mesh(new THREE.BoxGeometry(.12,.018,.018),hair));brow.position.set(x,3.72,.445);brow.rotation.z=x>0?-.08:.08;group.add(brow);});
  const nose=shadow(new THREE.Mesh(new THREE.SphereGeometry(.052,14,10),skin));nose.scale.set(.65,1,.9);nose.position.set(0,3.49,.47);group.add(nose);
  const mouth=shadow(new THREE.Mesh(new THREE.TorusGeometry(.085,.012,8,18,Math.PI),material(0x9a554c,.7)));mouth.position.set(0,3.37,.455);mouth.rotation.z=Math.PI;group.add(mouth);
  const makeArm=(side:number)=>{const pivot=new THREE.Group();pivot.position.set(side*.48,2.72,0);const upper=limb(.13,.62,coat);pivot.add(upper);const hand=shadow(new THREE.Mesh(new THREE.SphereGeometry(.145,16,12),skin));hand.position.set(0,-.77,.02);pivot.add(hand);group.add(pivot);return pivot;};
  const makeLeg=(side:number)=>{const pivot=new THREE.Group();pivot.position.set(side*.22,1.72,0);const leg=limb(.15,.83,dark);pivot.add(leg);const shoe=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(.16,.26,8,14),boot));shoe.rotation.x=Math.PI/2;shoe.position.set(0,-1.05,.12);pivot.add(shoe);group.add(pivot);return pivot;};
  const leftArm=makeArm(-1),rightArm=makeArm(1),leftLeg=makeLeg(-1),rightLeg=makeLeg(1);group.scale.setScalar(1.06);
  return{group,leftArm,rightArm,leftLeg,rightLeg,body,face};
}

function createEnemy(index:number):FighterParts{
  const group=new THREE.Group();group.name=`夜の影 ${index+1}`;
  const skin=material(index%2?0xa87963:0xb48669,.82),cloth=material(index%2?0x394c4b:0x4f3d48,.82),dark=material(0x171d1d,.9),mask=material(index===3?0xa64b3d:0x263330,.64),eye=material(0xe9c873,.35);
  const body=shadow(new THREE.Mesh(new THREE.CapsuleGeometry(.48,1,8,18),cloth));body.position.y=2.16;body.scale.set(.9,1,.7);group.add(body);
  const face=shadow(new THREE.Mesh(new THREE.SphereGeometry(.46,28,20),skin));face.scale.set(.84,1,.9);face.position.y=3.48;group.add(face);
  const hood=shadow(new THREE.Mesh(new THREE.SphereGeometry(.49,26,18,0,Math.PI*2,0,Math.PI*.63),dark));hood.position.set(0,3.64,-.03);group.add(hood);
  const faceMask=shadow(new THREE.Mesh(new THREE.BoxGeometry(.62,.3,.08),mask));faceMask.position.set(0,3.42,.42);faceMask.rotation.x=-.08;group.add(faceMask);
  [-.14,.14].forEach(x=>{const e=shadow(new THREE.Mesh(new THREE.SphereGeometry(.035,10,8),eye));e.position.set(x,3.59,.43);group.add(e);});
  const makeArm=(side:number)=>{const pivot=new THREE.Group();pivot.position.set(side*.5,2.68,0);pivot.add(limb(.15,.68,cloth));const fist=shadow(new THREE.Mesh(new THREE.SphereGeometry(.17,14,10),skin));fist.position.set(0,-.82,.02);pivot.add(fist);group.add(pivot);return pivot;};
  const makeLeg=(side:number)=>{const pivot=new THREE.Group();pivot.position.set(side*.23,1.62,0);pivot.add(limb(.17,.84,dark));group.add(pivot);return pivot;};
  const leftArm=makeArm(-1),rightArm=makeArm(1),leftLeg=makeLeg(-1),rightLeg=makeLeg(1);return{group,leftArm,rightArm,leftLeg,rightLeg,body,face};
}

function addStage(scene:THREE.Scene){
  const road=shadow(new THREE.Mesh(new THREE.PlaneGeometry(50,10),new THREE.MeshStandardMaterial({color:0x263c39,roughness:.92,metalness:.02})));road.rotation.x=-Math.PI/2;road.position.set(17,0,0);scene.add(road);
  const edge=shadow(new THREE.Mesh(new THREE.PlaneGeometry(52,3),material(0x152d28,.95)));edge.rotation.x=-Math.PI/2;edge.position.set(17,-.02,-6.4);scene.add(edge);const edge2=edge.clone();edge2.position.z=6.4;scene.add(edge2);
  const stripeMaterial=new THREE.MeshBasicMaterial({color:0xa78f57,transparent:true,opacity:.35});for(let x=-5;x<42;x+=4){const stripe=new THREE.Mesh(new THREE.PlaneGeometry(1.6,.06),stripeMaterial);stripe.rotation.x=-Math.PI/2;stripe.position.set(x,.015,0);scene.add(stripe);}
  const trunk=material(0x3d3028,.92),leaves=material(0x1e4c3a,.9);for(let i=0;i<14;i++){const x=-3+i*3.5,tree=new THREE.Group();const t=shadow(new THREE.Mesh(new THREE.CylinderGeometry(.16,.24,3.5,10),trunk));t.position.y=1.75;tree.add(t);const crown=shadow(new THREE.Mesh(new THREE.IcosahedronGeometry(1.25,1),leaves));crown.position.y=3.9;tree.add(crown);tree.position.set(x,0,-6.1-(i%3)*.35);scene.add(tree);}
  for(let i=0;i<7;i++){const post=shadow(new THREE.Mesh(new THREE.CylinderGeometry(.05,.08,2.5,10),material(0x332d28,.55,.28)));post.position.set(i*6-1,1.25,-5);scene.add(post);const lamp=shadow(new THREE.Mesh(new THREE.BoxGeometry(.38,.48,.32),material(0xe1b855,.35,.1)));lamp.position.set(i*6-1,2.48,-5);scene.add(lamp);const light=new THREE.PointLight(0xffc96c,4.2,7,2);light.position.set(i*6-1,2.45,-4.75);scene.add(light);}
  const gate=shadow(new THREE.Mesh(new THREE.BoxGeometry(.45,5.4,.45),material(0x3a2923,.8)));gate.position.set(35,2.7,-4.7);scene.add(gate);const gate2=gate.clone();gate2.position.z=4.7;scene.add(gate2);const beam=shadow(new THREE.Mesh(new THREE.BoxGeometry(.5,.45,9.8),material(0x6e3d2d,.78)));beam.position.set(35,5.25,0);scene.add(beam);
  const sign=shadow(new THREE.Mesh(new THREE.BoxGeometry(.15,1.1,3.4),material(0x263b34,.72)));sign.position.set(34.9,4.55,0);scene.add(sign);
}

export default function Brawler3DGame({onClear}:Props){
  const mountRef=useRef<HTMLDivElement>(null),onClearRef=useRef(onClear),resetScene=useRef<()=>void>(()=>undefined),attackRequest=useRef(false),input=useRef<InputState>({left:false,right:false,up:false,down:false});
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[health,setHealth]=useState(100),[remaining,setRemaining]=useState(4),[combo,setCombo]=useState(0),[score,setScore]=useState(0),[finished,setFinished]=useState(false),[message,setMessage]=useState("夜の研究路をふさいでいる影を静め、森研究所の門へ進みます。");
  useEffect(()=>{onClearRef.current=onClear;},[onClear]);
  const attack=useCallback(()=>{if(!finished)attackRequest.current=true;},[finished]);
  const reset=useCallback(()=>{input.current={left:false,right:false,up:false,down:false};attackRequest.current=false;setHealth(100);setRemaining(4);setCombo(0);setScore(0);setFinished(false);setMessage("夜の研究路をふさいでいる影を静め、森研究所の門へ進みます。");resetScene.current();},[]);
  useEffect(()=>{const host=mountRef.current;if(!host)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});}catch{const timer=window.setTimeout(()=>{setError("この3D実験版はM1以降のiPad、またはWebGL対応端末向けです。");setLoading(false);},0);return()=>window.clearTimeout(timer);}renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.domElement.setAttribute("aria-label","ミナが夜の研究路で影と戦うリアル寄り3Dベルトスクロール画面");host.appendChild(renderer.domElement);
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x101d27);scene.fog=new THREE.Fog(0x101d27,24,58);const camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(-7,6.3,12);scene.add(new THREE.HemisphereLight(0x9fc8d8,0x11221c,1.7));const moon=new THREE.DirectionalLight(0xc7dcff,3.2);moon.position.set(-8,14,9);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-18;moon.shadow.camera.right=18;moon.shadow.camera.top=16;moon.shadow.camera.bottom=-12;scene.add(moon);addStage(scene);
    const mina=createMina();mina.group.position.set(0,0,0);mina.group.rotation.y=Math.PI/2;scene.add(mina.group);const spawn=[{x:8,z:-1.8},{x:14,z:2.2},{x:21,z:-2.4},{x:28,z:1.2}];const enemies:Enemy[]=spawn.map((p,i)=>{const fighter=createEnemy(i);fighter.group.position.set(p.x,0,p.z);fighter.group.rotation.y=-Math.PI/2;scene.add(fighter.group);return{fighter,health:i===3?150:100,active:true,attackCooldown:1+i*.3,hitFlash:0,homeZ:p.z};});
    let playerHealth=100,scoreValue=0,comboValue=0,comboTimer=0,attackTime=0,attackCooldown=0,invincible=0,walkTime=0,lastFacing=1,raf=0,cleared=false;
    const restore=()=>{mina.group.position.set(0,0,0);mina.group.visible=true;playerHealth=100;scoreValue=0;comboValue=0;comboTimer=0;attackTime=0;attackCooldown=0;invincible=0;cleared=false;enemies.forEach((enemy,i)=>{enemy.active=true;enemy.health=i===3?150:100;enemy.attackCooldown=1+i*.3;enemy.hitFlash=0;enemy.fighter.group.visible=true;enemy.fighter.group.position.set(spawn[i].x,0,spawn[i].z);enemy.fighter.body.material=material(i%2?0x394c4b:0x4f3d48,.82);});};resetScene.current=restore;
    const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();
    const keydown=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if(["arrowleft","arrowright","arrowup","arrowdown","a","d","w","s","j"," "].includes(key))event.preventDefault();if(key==="arrowleft"||key==="a")input.current.left=true;if(key==="arrowright"||key==="d")input.current.right=true;if(key==="arrowup"||key==="w")input.current.up=true;if(key==="arrowdown"||key==="s")input.current.down=true;if(key==="j"||key===" ")attackRequest.current=true;};const keyup=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if(key==="arrowleft"||key==="a")input.current.left=false;if(key==="arrowright"||key==="d")input.current.right=false;if(key==="arrowup"||key==="w")input.current.up=false;if(key==="arrowdown"||key==="s")input.current.down=false;};window.addEventListener("keydown",keydown);window.addEventListener("keyup",keyup);
    const clock=new THREE.Clock();const animate=()=>{raf=requestAnimationFrame(animate);const delta=Math.min(clock.getDelta(),.04);walkTime+=delta;attackCooldown=Math.max(0,attackCooldown-delta);attackTime=Math.max(0,attackTime-delta);comboTimer=Math.max(0,comboTimer-delta);invincible=Math.max(0,invincible-delta);if(comboTimer===0&&comboValue!==0){comboValue=0;setCombo(0);}
      if(!cleared&&playerHealth>0){const dx=(input.current.right?1:0)-(input.current.left?1:0),dz=(input.current.down?1:0)-(input.current.up?1:0),length=Math.hypot(dx,dz)||1;mina.group.position.x=clamp(mina.group.position.x+dx/length*delta*5.2,-2,34);mina.group.position.z=clamp(mina.group.position.z+dz/length*delta*4.1,-3.8,3.8);if(dx!==0)lastFacing=dx>0?1:-1;mina.group.rotation.y+=(lastFacing*Math.PI/2-mina.group.rotation.y)*Math.min(1,delta*10);const moving=Math.abs(dx)+Math.abs(dz)>0;const stride=moving?Math.sin(walkTime*10)*.58:0;mina.leftLeg.rotation.x+=(stride-mina.leftLeg.rotation.x)*Math.min(1,delta*12);mina.rightLeg.rotation.x+=(-stride-mina.rightLeg.rotation.x)*Math.min(1,delta*12);if(attackRequest.current&&attackCooldown<=0){attackRequest.current=false;attackCooldown=.34;attackTime=.28;comboValue=comboTimer>0?comboValue%3+1:1;comboTimer=.8;setCombo(comboValue);let hit=false;enemies.forEach(enemy=>{if(!enemy.active)return;const ex=enemy.fighter.group.position.x-mina.group.position.x,ez=Math.abs(enemy.fighter.group.position.z-mina.group.position.z);if(ex*lastFacing>-.35&&Math.abs(ex)<2.45&&ez<1.35){hit=true;const damage=comboValue===3?55:38;enemy.health-=damage;enemy.hitFlash=.16;enemy.fighter.group.position.x+=lastFacing*(comboValue===3?1.8:.8);scoreValue+=comboValue===3?350:180;setScore(scoreValue);if(enemy.health<=0){enemy.active=false;enemy.fighter.group.visible=false;const left=enemies.filter(item=>item.active).length;setRemaining(left);setMessage(left?`影を一体静めました。残り ${left}体です。`:"研究路の影がすべて消えました。森研究所の門が開きます。");}}});setMessage(hit?(comboValue===3?"三段目が決まり、影を大きく吹き飛ばしました！":"攻撃が影をとらえました。続けて押すと三段攻撃になります。"):`攻撃 ${comboValue}。影との奥行きを合わせます。`);}
        const punch=attackTime>0?Math.sin((.28-attackTime)/.28*Math.PI):0;mina.rightArm.rotation.x+=(-punch*1.9-mina.rightArm.rotation.x)*Math.min(1,delta*20);mina.leftArm.rotation.x+=((comboValue===3?-punch*1.45:-punch*.28)-mina.leftArm.rotation.x)*Math.min(1,delta*18);
        enemies.forEach(enemy=>{if(!enemy.active)return;enemy.attackCooldown=Math.max(0,enemy.attackCooldown-delta);enemy.hitFlash=Math.max(0,enemy.hitFlash-delta);const ex=mina.group.position.x-enemy.fighter.group.position.x,ez=mina.group.position.z-enemy.fighter.group.position.z,distance=Math.hypot(ex,ez);if(distance<9&&distance>1.45){enemy.fighter.group.position.x+=ex/distance*delta*1.65;enemy.fighter.group.position.z+=ez/distance*delta*1.3;}enemy.fighter.group.rotation.y+=((ex>0?Math.PI/2:-Math.PI/2)-enemy.fighter.group.rotation.y)*Math.min(1,delta*7);const enemyStride=Math.sin(walkTime*8+enemy.homeZ)*.38;enemy.fighter.leftLeg.rotation.x=distance>1.5?enemyStride:0;enemy.fighter.rightLeg.rotation.x=distance>1.5?-enemyStride:0;enemy.fighter.rightArm.rotation.x=distance<1.7?Math.sin(walkTime*12)*-.8:0;if(distance<1.6&&enemy.attackCooldown<=0&&invincible<=0){enemy.attackCooldown=1.2;invincible=.75;playerHealth=clamp(playerHealth-(enemy.health>100?16:11),0,100);setHealth(playerHealth);mina.group.position.x-=Math.sign(ex)*.65;setMessage(playerHealth>0?"影の反撃を受けました。奥・手前へ動いて囲まれないようにします。":"ミナは一度、研究路の入口へ戻ります。");if(playerHealth<=0)mina.group.visible=false;}});
        if(enemies.every(enemy=>!enemy.active)&&!cleared){cleared=true;setFinished(true);setMessage("研究路を通れるようになりました。ミナが森研究所の門へ到着しました！");onClearRef.current();}
      }
      const targetX=mina.group.visible?mina.group.position.x:0;camera.position.x+=(targetX-7-camera.position.x)*Math.min(1,delta*3);camera.position.y=6.2;camera.position.z=11.5;camera.lookAt(targetX+2,2,0);renderer.render(scene,camera);};const ready=setTimeout(()=>setLoading(false),0);animate();return()=>{clearTimeout(ready);cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener("keydown",keydown);window.removeEventListener("keyup",keyup);scene.traverse(object=>{if(!(object instanceof THREE.Mesh))return;object.geometry.dispose();const mats=Array.isArray(object.material)?object.material:[object.material];mats.forEach(item=>item.dispose());});renderer.dispose();renderer.domElement.remove();resetScene.current=()=>undefined;};
  },[]);
  const setDirection=useCallback((key:keyof InputState,value:boolean,event:ReactPointerEvent<HTMLButtonElement>)=>{if(value)event.currentTarget.setPointerCapture(event.pointerId);else if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);input.current[key]=value;},[]);
  return <div className="brawler-game"><div className="brawler-stage" ref={mountRef}>{loading&&<div className="brawler-loading"><span>M1 3D BRAWLER ENGINE</span><strong>夜の研究路を構築しています…</strong></div>}{error&&<div className="brawler-loading"><span>DEVICE NOTICE</span><strong>{error}</strong></div>}<div className="brawler-hud"><div><small>MINA</small><div className="brawler-health"><i style={{width:`${health}%`}}/></div><strong>{health}</strong></div><div><small>NIGHT SHADOWS</small><strong>{remaining}<i> / 4</i></strong></div><div><small>SCORE</small><strong>{score}</strong></div>{combo>1&&<div className="brawler-combo">{combo} HIT</div>}</div><div className="brawler-title"><span>MISSION 02 · NIGHT RESEARCH ROAD</span><strong>影を静め、森研究所の門へ</strong></div></div>
    <div className="brawler-console"><p aria-live="polite">{message}</p><div className="brawler-controls"><div className="brawler-dpad"><button aria-label="奥へ" onPointerDown={e=>setDirection("up",true,e)} onPointerUp={e=>setDirection("up",false,e)} onPointerCancel={e=>setDirection("up",false,e)}>↑</button><button aria-label="左へ" onPointerDown={e=>setDirection("left",true,e)} onPointerUp={e=>setDirection("left",false,e)} onPointerCancel={e=>setDirection("left",false,e)}>←</button><button aria-label="手前へ" onPointerDown={e=>setDirection("down",true,e)} onPointerUp={e=>setDirection("down",false,e)} onPointerCancel={e=>setDirection("down",false,e)}>↓</button><button aria-label="右へ" onPointerDown={e=>setDirection("right",true,e)} onPointerUp={e=>setDirection("right",false,e)} onPointerCancel={e=>setDirection("right",false,e)}>→</button></div><button className="brawler-attack" onPointerDown={attack} disabled={finished||Boolean(error)}>攻撃</button><button className="brawler-reset" onClick={reset}>最初から</button></div><div className="brawler-note"><span>攻撃を続けて押すと3段コンボ。敵との奥行きを合わせます。</span><span>← → ↑ ↓ / WASD / J・Space</span></div></div>{finished&&<div className="brawler-result"><strong>夜の研究路を通過しました</strong><p>スコア {score}　ミナの体力 {health}</p><button onClick={reset}>もう一度、研究路へ</button></div>}</div>;
}
